# Generated by Django 3.2.19 on 2023-05-07 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='descript',
            new_name='description',
        ),
    ]
